config/routes.rb
Giftnetwork::Application.routes.draw do
  
  get "deal_display/index"

  resources :daily_deal_tags

  resources :daily_deal_locations

  resources :daily_deals

  get "admin_panel/index"

  resources :posts

  resources :wishlists

  get "dashboard/index"

  devise_for :members
  
  namespace :members do
    get "dashboard/index"
    resources :wishlists
    root :to => "dashboard#index"
  end
  
  namespace :admin do
    resources :posts
    root :to => "admin_panel#index"
    match 'refresh_yipit' => 'admin_panel#refresh_yipit'
  end

  get "home/index"
  
  match 'search_results' => 'home#search_results'
  match 'entertainment_results' => 'home#entertainment_results'
  match 'entertainment' => 'home#entertainment'
  match 'services' => 'home#services'
  match 'search_result/:item' => 'home#search_result'
  
  root :to => "home#index"

end

app/models/daily_deal.rb
class DailyDeal < ActiveRecord::Base
  has_many :daily_deal_locations
end

app/models/daily_deal_location.rb
class DailyDealLocation < ActiveRecord::Base
  acts_as_gmappable
  belongs_to :daily_deal
  def gmaps4rails_address
    #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    "#{self.address}, #{self.city}, #{self.state}, #{self.zip}"
  end
  def gmaps4rails_infowindow
    "<img src='#{self.daily_deal.small_image}' align='left' style='max-height:100px;margin-right:15px;' /><b>#{self.daily_deal.yipit_title}</b><br>Found through: #{self.daily_deal.source_name}<br><br><a href='members/get_notified/#{self.daily_deal.id}'>Get notified about this deal</a>"
  end
end

app/models/daily_deal_tag.rb
class DailyDealTag < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :wishlists
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  has_friendly_id :title, :use_slug => true
  
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  
  belongs_to :member
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'application'
  protect_from_forgery
end

app/controllers/daily_deal_locations_controller.rb
class DailyDealLocationsController < InheritedResources::Base
end

app/controllers/daily_deals_controller.rb
class DailyDealsController < InheritedResources::Base
end

app/controllers/deal_display_controller.rb
class DealDisplayController < ApplicationController
  def index
    @json = DailyDealLocation.all.to_gmaps4rails
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'none'
  def index
  end
  def search_results
    # Amazon
    request = Sucker.new( :locale => :us, :key => 'AKIAJY7TE7TS3ZZVIIDA', :secret => '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')
    request << {'Operation' => 'ItemSearch', 'SearchIndex' => 'All', 'Keywords' => params[:name], 'ResponseGroup' => 'Medium' }
    @response = request.get
    
    # Best Buy
    require 'open-uri'
    @best_buy_result = ActiveSupport::JSON.decode(open("http://api.remix.bestbuy.com/v1/products(search=#{params[:name]})?apiKey=9zvesrz4hn94ems64x47pqcd&format=json").read)
    
  end
  def entertainment_results
    #Groupon
    require 'open-uri'
    query = ActiveSupport::JSON.decode(open("http://api.groupon.com/v2/deals/?client_id=1264602292deb8d881b0e32282785495dd783bf8").read)
    @groupon_result = query.to_hash
  end
  
  def search_result
    
  end
  
  
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  layout 'blog'
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_deal_locations_helper.rb
module DailyDealLocationsHelper
end

app/helpers/daily_deal_tags_helper.rb
module DailyDealTagsHelper
end

app/helpers/daily_deals_helper.rb
module DailyDealsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/deal_display_helper.rb
module DealDisplayHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def getAmazonImage(asin)
    image_request = Sucker.new( :locale => :us, :key => 'AKIAJY7TE7TS3ZZVIIDA', :secret => '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')
    image_request << {'Operation' => 'ItemLookup', 'IdType' => 'ASIN', 'ItemId' => asin, 'ResponseGroup' => 'Images'}
    image_response = image_request.get
    image_response.each('Item') do |image|
      if image['SmallImage'] != nil
        return image['SmallImage']['URL']
      else
        return false
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/daily_deal_locations/_form.html.haml
= simple_form_for(@daily_deal_location) do |f|
  - if @daily_deal_location.errors.any?
    #error_explanation
      %h2
        = pluralize(@daily_deal_location.errors.count, "error")
        prohibited this daily_deal_location from being saved:

      %ul
        - @daily_deal_location.errors.full_messages.each do |msg|
          %li= msg

  .inputs
    = f.input :yipit_id
    = f.input :address
    = f.input :city
    = f.input :state
    = f.input :zip
    = f.input :phone
    = f.input :lat
    = f.input :lon
    = f.input :daily_deal_id

  .actions
    = f.button :submit

app/views/daily_deal_locations/edit.html.haml
%h1 Editing daily_deal_location

= render 'form'

= link_to 'Show', @daily_deal_location
\|
= link_to 'Back', daily_deal_locations_path

app/views/daily_deal_locations/index.html.haml
%h1 Listing daily_deal_locations

%table
  %tr
    %th Yipit
    %th Address
    %th City
    %th State
    %th Zip
    %th Phone
    %th Lat
    %th Lon
    %th Daily deal
    %th
    %th
    %th

  - @daily_deal_locations.each do |daily_deal_location|
    %tr
      %td= daily_deal_location.yipit_id
      %td= daily_deal_location.address
      %td= daily_deal_location.city
      %td= daily_deal_location.state
      %td= daily_deal_location.zip
      %td= daily_deal_location.phone
      %td= daily_deal_location.lat
      %td= daily_deal_location.lon
      %td= daily_deal_location.daily_deal_id
      %td= link_to 'Show', daily_deal_location
      %td= link_to 'Edit', edit_daily_deal_location_path(daily_deal_location)
      %td= link_to 'Destroy', daily_deal_location, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Daily deal location', new_daily_deal_location_path

app/views/daily_deal_locations/new.html.haml
%h1 New daily_deal_location

= render 'form'

= link_to 'Back', daily_deal_locations_path

app/views/daily_deal_locations/show.html.haml
%p#notice= notice

%p
  %b Yipit:
  = @daily_deal_location.yipit_id
%p
  %b Address:
  = @daily_deal_location.address
%p
  %b City:
  = @daily_deal_location.city
%p
  %b State:
  = @daily_deal_location.state
%p
  %b Zip:
  = @daily_deal_location.zip
%p
  %b Phone:
  = @daily_deal_location.phone
%p
  %b Lat:
  = @daily_deal_location.lat
%p
  %b Lon:
  = @daily_deal_location.lon
%p
  %b Daily deal:
  = @daily_deal_location.daily_deal_id

= link_to 'Edit', edit_daily_deal_location_path(@daily_deal_location)
\|
= link_to 'Back', daily_deal_locations_path