config/routes.rb
Giftnetwork::Application.routes.draw do
  
  get "deal_display/index"

  resources :daily_deal_tags

  resources :daily_deal_locations

  resources :daily_deals

  get "admin_panel/index"

  resources :posts

  resources :wishlists

  get "dashboard/index"

  devise_for :members
  
  namespace :members do
    get "dashboard/index"
    resources :wishlists
    root :to => "dashboard#index"
  end
  
  namespace :admin do
    resources :posts
    root :to => "admin_panel#index"
    match 'refresh_yipit' => 'admin_panel#refresh_yipit'
  end

  get "home/index"
  
  match 'search_results' => 'home#search_results'
  match 'entertainment_results' => 'home#entertainment_results'
  match 'entertainment' => 'home#entertainment'
  match 'services' => 'home#services'
  match 'search_result/:item' => 'home#search_result'
  
  root :to => "home#index"

end

app/models/daily_deal.rb
class DailyDeal < ActiveRecord::Base
  has_many :daily_deal_locations
end

app/models/daily_deal_location.rb
class DailyDealLocation < ActiveRecord::Base
  acts_as_gmappable
  belongs_to :daily_deal
  def gmaps4rails_address
    #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    "#{self.address}, #{self.city}, #{self.state}, #{self.zip}"
  end
  def gmaps4rails_infowindow
    "<img src='#{self.daily_deal.small_image}' align='left' style='max-height:100px;margin-right:15px;' /><b>#{self.daily_deal.yipit_title}</b><br>Found through: #{self.daily_deal.source_name}<br><br><a href='members/get_notified/#{self.daily_deal.id}'>Get notified about this deal</a>"
  end
end

app/models/daily_deal_tag.rb
class DailyDealTag < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :wishlists
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  has_friendly_id :title, :use_slug => true
  
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  
  belongs_to :member
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'application'
  protect_from_forgery
end

app/controllers/daily_deals_controller.rb
class DailyDealsController < InheritedResources::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'none'
  def index
  end
  def search_results
    # Amazon
    request = Sucker.new( :locale => :us, :key => 'AKIAJY7TE7TS3ZZVIIDA', :secret => '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')
    request << {'Operation' => 'ItemSearch', 'SearchIndex' => 'All', 'Keywords' => params[:name], 'ResponseGroup' => 'Medium' }
    @response = request.get
    
    # Best Buy
    require 'open-uri'
    @best_buy_result = ActiveSupport::JSON.decode(open("http://api.remix.bestbuy.com/v1/products(search=#{params[:name]})?apiKey=9zvesrz4hn94ems64x47pqcd&format=json").read)
    
  end
  def entertainment_results
    #Groupon
    require 'open-uri'
    query = ActiveSupport::JSON.decode(open("http://api.groupon.com/v2/deals/?client_id=1264602292deb8d881b0e32282785495dd783bf8").read)
    @groupon_result = query.to_hash
  end
  
  def search_result
    
  end
  
  
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  layout 'blog'
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_deal_tags_helper.rb
module DailyDealTagsHelper
end

app/helpers/daily_deals_helper.rb
module DailyDealsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/deal_display_helper.rb
module DealDisplayHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def getAmazonImage(asin)
    image_request = Sucker.new( :locale => :us, :key => 'AKIAJY7TE7TS3ZZVIIDA', :secret => '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')
    image_request << {'Operation' => 'ItemLookup', 'IdType' => 'ASIN', 'ItemId' => asin, 'ResponseGroup' => 'Images'}
    image_response = image_request.get
    image_response.each('Item') do |image|
      if image['SmallImage'] != nil
        return image['SmallImage']['URL']
      else
        return false
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title #{yield :title} SpyTheBuy
    = stylesheet_link_tag 'admin'
    = javascript_include_tag :defaults
    = csrf_meta_tag

%body
  #container
    #header
      %h1 Admin
    #navigation
      %ul
        %li= link_to 'Admin Dashboard', admin_root_path
        %li= link_to 'Refresh Yipit Base', admin_refresh_yipit_path
    #content
      = yield
    #footer

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title #{yield :title} SpytheBuy
    = stylesheet_link_tag 'application'
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield :head

%body
  #container
    #header
      - if member_signed_in?
        = link_to 'My wishlist', members_wishlists_path
      - else
        = link_to 'Sign in', '/members/sign_in'
      %h1 Welcome to SpytheBuy
        
      
    #navigation
      %ul
        %li= link_to 'things', '/'
        %li= link_to 'services', services_path
        %li= link_to 'entertainment', entertainment_path
        
    #content
    = yield
    
    #footer
      %p &copy; Copyright 2011 The Gift Network. All Rights Reserved.

app/views/layouts/blog.html.haml
!!!
%html
  %head
    %title #{yield :title} SpyTheBuy
    = stylesheet_link_tag 'application'
    = javascript_include_tag :defaults
    = csrf_meta_tag

%body
  #header
    #container
      %h1 SpyTheBuy
  #content
    #container
      = yield
    
  #footer
    #container
      %p &copy; Copyright 2011 SpyTheBuy. All Rights Reserved.

app/views/layouts/none.html.haml
!!!
%html
  %head
    %title #{yield :title} SpytheBuy
    = stylesheet_link_tag 'application'
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield :head

%body
  = yield